version: '3.9'

services:
  web_server_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'cq-be'
    ports:
      - '8082:80'
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./.docker/server/apache/sites-enabled:/etc/apache2/sites-enabled
      - ./.docker/server/php:/usr/local/etc/php/conf.d/extra-php-config.ini
